version: '3.7'
services:
  gnome-stats:
    network_mode: "host"
    container_name: gnome-stats
    restart: always
    build:
      context: ./GNOME-stats
      dockerfile: Dockerfile.dev
      target: dev
    environment:
        - CHOKIDAR_USEPOLLING=true
        - PORT=${PORT}
    ports:
      - '8080:80' # prod
      - '5174:5174' # dev
    volumes:
      - ./GNOME-stats:/app:rw
      - /app/node_modules
